// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Reborn_Zune_MusicLibraryEFCoreModel.Migrations
{
    [DbContext(typeof(MusicLibraryDbContext))]
    partial class MusicLibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("MusicLibraryEFCoreModel.Music", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasMaxLength(450)
                        .IsUnicode(true);

                    b.Property<string>("AlbumArtist")
                        .IsRequired()
                        .HasColumnName("AlbumArtist")
                        .IsUnicode(true);

                    b.Property<string>("AlbumTitle");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnName("Artist")
                        .IsUnicode(true);

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnName("Duration")
                        .IsUnicode(true);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnName("Path")
                        .IsUnicode(true);

                    b.Property<string>("ThumbnailId")
                        .HasColumnName("ThumbnailId")
                        .IsUnicode(true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("Title")
                        .IsUnicode(true);

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnName("Year")
                        .IsUnicode(true);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasName("UQ__Music__AUQKR5RFNOUO6UFR");

                    b.HasIndex("ThumbnailId");

                    b.ToTable("Music");
                });

            modelBuilder.Entity("MusicLibraryEFCoreModel.MusicInPlaylist", b =>
                {
                    b.Property<string>("MusicId")
                        .HasColumnName("MusicId")
                        .HasMaxLength(450)
                        .IsUnicode(true);

                    b.Property<string>("PlaylistId")
                        .HasColumnName("PlaylistId")
                        .HasMaxLength(450)
                        .IsUnicode(true);

                    b.HasKey("MusicId", "PlaylistId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("MusicInPlaylist");
                });

            modelBuilder.Entity("MusicLibraryEFCoreModel.Playlist", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasMaxLength(450)
                        .IsUnicode(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .IsUnicode(true);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasName("UQ__Playlist__AUQKR5RFNOUO6UFR");

                    b.ToTable("Playlst");
                });

            modelBuilder.Entity("MusicLibraryEFCoreModel.Thumbnail", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasMaxLength(450)
                        .IsUnicode(true);

                    b.Property<byte[]>("ImageBytes")
                        .IsRequired()
                        .HasColumnName("Image")
                        .HasColumnType("BLOB")
                        .IsUnicode(true);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasName("UQ__Thumbnail__AUQKR5RFNOUO6UFR");

                    b.ToTable("Thumbnail");
                });

            modelBuilder.Entity("MusicLibraryEFCoreModel.Music", b =>
                {
                    b.HasOne("MusicLibraryEFCoreModel.Thumbnail", "Thumbnail")
                        .WithMany("Musics")
                        .HasForeignKey("ThumbnailId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MusicLibraryEFCoreModel.MusicInPlaylist", b =>
                {
                    b.HasOne("MusicLibraryEFCoreModel.Music", "Music")
                        .WithMany("MusicInPlaylists")
                        .HasForeignKey("MusicId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MusicLibraryEFCoreModel.Playlist", "Playlist")
                        .WithMany("MusicInPlaylists")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
